[build-system]
requires = ["setuptools>=61.0.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cv2-helper"
dynamic = ["version"]
description = "Una librería auxiliar para OpenCV"
readme = "README.md"
authors = [
    { name = "Pedro Mayorga", email = "ppmayorga80@gmail.com" }
]
license = "MIT"
requires-python = ">=3.8"
dependencies = [
    "opencv-python>=4.0.0"
]

[tool.setuptools_scm]

[tool.semantic_release]
version_variables = [
    "cv2_helper/__init__.py:__version__"
]
build_command = "pip install build && python -m build"

[tool.semantic_release.branches.main]
match = "main"

[tool.semantic_release.pypi]
upload = true

[tool.semantic_release.remote]
type = "github"
token = "env:GH_TOKEN"